<a href="https://colab.research.google.com/github/MeSamiulIslam/aiQuest/blob/main/assignment_09_knn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
from sklearn.model_selection import train_test_split

In [3]:
url = 'https://raw.githubusercontent.com/MeSamiulIslam/aiQuest/main/weight-height.csv'
df = pd.read_csv(url) #df = pd.read_csv(url)
df.head(5)

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [4]:
df1 = df.copy()
df2 = df.copy()

In [5]:
df.Gender = le.fit_transform(df[['Gender']])
df.head(5)

Gender     Height      Weight
0       1  73.847017  241.893563
1       1  68.781904  162.310473
2       1  74.110105  212.740856
3       1  71.730978  220.042470
4       1  69.881796  206.349801

In [7]:
X = df.iloc[:, 0:2] #Seperate x
y = df.iloc[:, 2] #Seperate y

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)

In [9]:
X_test.shape

(2567, 2)

In [10]:
X_train.shape

(5988, 2)

In [11]:
X.shape

(8555, 2)

In [12]:
df.isnull().sum()

Gender    0
Height    0
Weight    0
dtype: int64

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
LReg = LinearRegression()
m_s_e = mean_squared_error

In [14]:
LReg.fit(X_train, y_train) # training the maodel

LinearRegression()

In [15]:
LReg.predict([[1,73]])

array([210.91818416])

In [67]:
linear_regression = LReg.score(X_test, y_test) # training sccuracy 
linear_regression

0.9010685212826652

In [17]:
LReg.predict(X_test)

array([143.65660829, 145.37939481, 201.08956661, ..., 179.02672324,
       135.53135391, 182.38222536])

In [18]:
X_train['Predict_Weight'] = LReg.predict(X_train)

In [19]:
X_train.head()

Gender     Height  Predict_Weight
869        1  67.697104      179.172248
8185       0  63.717034      135.691400
5322       0  60.845508      118.500932
5993       0  63.008067      131.447150
3358       1  71.304176      200.766085

In [21]:
mse_lr =  m_s_e(y_train, X_train.Predict_Weight) #Calculate Mean Square Error

In [22]:
mse_lr

102.99673340725141

#KNN Regressor with weight=distance:

In [23]:
from sklearn.neighbors import KNeighborsRegressor
KNR = KNeighborsRegressor(n_neighbors=100, weights='distance')

In [26]:
df1.Gender = le.fit_transform(df1[['Gender']])
df1.head(5)

Gender     Height      Weight
0       1  73.847017  241.893563
1       1  68.781904  162.310473
2       1  74.110105  212.740856
3       1  71.730978  220.042470
4       1  69.881796  206.349801

In [28]:
X1 = df1.iloc[:, :2] #Seperate x
y1 = df1.iloc[:, 2:3]  #Seperate y
X1.head(3)

Gender     Height
0       1  73.847017
1       1  68.781904
2       1  74.110105

In [29]:
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=0.30)

In [30]:
X1_test.shape

(2567, 2)

In [24]:
KNR.fit(X_train, y_train)

KNeighborsRegressor(n_neighbors=100, weights='distance')

In [31]:
KNR.fit(X1_train, y1_train)

KNeighborsRegressor(n_neighbors=100, weights='distance')

In [32]:
pred1 = KNR.predict(X1_test)
pred1

array([[174.71893142],
       [167.78638826],
       [183.40609862],
       ...,
       [140.05052796],
       [132.54586497],
       [186.58958842]])

In [34]:
mse_d = m_s_e(y1_test, pred1)
mse_d

119.66928298435091

In [68]:
KNN_Regression_Distance = r2_score(y1_test, pred1)
KNN_Regression_Distance

0.884057316420301

#KNN Regression with weight=uniform:

In [36]:
KNRu = KNeighborsRegressor(n_neighbors=100, weights='uniform')

In [37]:
KNRu.fit(X1_train, y1_train)

KNeighborsRegressor(n_neighbors=100)

In [39]:
pred2 = KNRu.predict(X1_test)
pred2

array([[175.57402796],
       [172.60864966],
       [183.95373419],
       ...,
       [142.83807078],
       [130.87232185],
       [187.41779975]])

In [41]:
mse_u = m_s_e(y1_test, pred2)
mse_u

105.57358490543848

In [69]:
KNN_Regression_Uniform = r2_score(y1_test, pred2)
KNN_Regression_Uniform

0.8977140629256848

#KNN Classifier with weight=distance:

In [43]:
from sklearn.neighbors import KNeighborsClassifier
KNC = KNeighborsClassifier(n_neighbors=100, weights='distance')

In [44]:
df2.Gender = le.fit_transform(df2[['Gender']])
df2.head(5)

Gender     Height      Weight
0       1  73.847017  241.893563
1       1  68.781904  162.310473
2       1  74.110105  212.740856
3       1  71.730978  220.042470
4       1  69.881796  206.349801

In [46]:
X2 = df2.iloc[:, 1:3] #Seperate x
y2 = df2.iloc[:, 0]  #Seperate y
X2.head(3)

Height      Weight
0  73.847017  241.893563
1  68.781904  162.310473
2  74.110105  212.740856

In [47]:
X2_train, X2_test, y2_train, y2_test = train_test_split(X2, y2, test_size=0.30)

In [48]:
X2_test.shape

(2567, 2)

In [49]:
KNC.fit(X2_train, y2_train)

KNeighborsClassifier(n_neighbors=100, weights='distance')

In [50]:
pred3 = KNC.predict(X2_test)
pred3

array([1, 0, 0, ..., 1, 0, 0])

In [51]:
mse_d2 = m_s_e(y2_test, pred3)
mse_d2

0.0806388780677834

In [72]:
KNN_Classifier_Distance2 = r2_score(y2_test, pred3)
KNN_Classifier_Distance2

0.6678175578102437

#KNN Classifier with weight=uniform:

In [53]:
KNCu = KNeighborsClassifier(n_neighbors=100, weights='uniform')

In [54]:
KNCu.fit(X2_train, y2_train)

KNeighborsClassifier(n_neighbors=100)

In [55]:
pred4 = KNCu.predict(X2_test)
pred4

array([1, 0, 0, ..., 1, 1, 0])

In [57]:
mse_u2 = m_s_e(y2_test, pred4)
mse_u2

0.08102843786521231

In [73]:
KNN_Classifier_Uniform2 = r2_score(y2_test, pred4)
KNN_Classifier_Uniform2

0.6662128117127086

#Compare models

In [74]:
names = ['linear_regression', 'KNN_Regression_Distance', 'KNN_Regression_Uniform', 'KNN_Classifier_Distance2', 'KNN_Classifier_Uniform2']
print("Best Model Accuracy is : ",end="")
print (max(names) )

Best Model Accuracy is : linear_regression
